#!/usr/bin/env bash
set -Eeuo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"
ENV_FILE=${STAGING_ENV_FILE:-.staging/phase15.env}
COMPOSE_FILE=docker-compose.staging.yml
mkdir -p .staging

if [[ ! -f "$ENV_FILE" ]]; then
  node scripts/generate-staging-env.mjs "$ENV_FILE"
fi

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

load_host_environment() {
  set -a
  # Generated by this repository from hex-only synthetic values.
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

wait_http() {
  local url=$1
  local attempts=${2:-60}
  for ((attempt = 1; attempt <= attempts; attempt++)); do
    if curl --fail --silent --show-error "$url" >/dev/null; then
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for $url" >&2
  return 1
}

collect_logs() {
  compose logs --no-color >.staging/topology.log 2>&1 || true
}

build_topology() {
  # Build targets serially so Docker Desktop does not materialize several
  # identical 1+ GiB pnpm builder layers in parallel on constrained disks.
  compose build migrate
  compose build seed
  compose build api
  compose build worker
  compose build web
  compose build api-ingress
}

cleanup() {
  if compose down --volumes --remove-orphans --timeout 30; then
    rm -f "$ENV_FILE"
  else
    echo "Staging cleanup failed; retaining $ENV_FILE for recovery" >&2
    return 1
  fi
}

finalize() {
  local status="$1"
  collect_logs
  if ! cleanup; then
    exit 1
  fi
  exit "$status"
}

run_gate() {
  trap 'finalize $?' EXIT

  compose down --volumes --remove-orphans --timeout 30
  build_topology
  compose up -d --wait postgres temporal minio
  compose run --rm --no-deps temporal-namespace
  compose run --rm --no-deps migrate
  compose run --rm --no-deps seed

  compose run --rm --no-deps test-runner
  compose run --rm --no-deps seed

  compose up -d --wait api worker web api-ingress web-ingress
  load_host_environment
  wait_http http://localhost:3001/api/health/live
  wait_http http://localhost:3001/api/health/ready
  wait_http http://localhost:3000/login

  if compose exec -T api node -e "fetch('https://example.com',{signal:AbortSignal.timeout(5000)}).then(()=>process.exit(0)).catch(()=>process.exit(1))"; then
    echo 'External network egress is available to the API container' >&2
    return 1
  fi

  local migrations
  migrations=$(compose exec -T postgres psql -U "$STAGING_POSTGRES_USER" -d "$STAGING_POSTGRES_DB" -Atc 'select count(*) from "_prisma_migrations" where finished_at is not null and rolled_back_at is null')
  [[ "$migrations" == '11' ]] || { echo "Expected 11 applied migrations, found $migrations" >&2; return 1; }

  local workflows_before workflows_after
  workflows_before=$(compose exec -T temporal sh -ec 'tctl --address "$(hostname -i):7233" workflow list --namespace ventureos-staging --pagesize 1000 2>/dev/null | wc -l')
  for _ in 1 2 3 4 5; do
    curl --fail --silent http://localhost:3001/api/health/ready >/dev/null
    curl --fail --silent http://localhost:3001/api/health/temporal >/dev/null
  done
  workflows_after=$(compose exec -T temporal sh -ec 'tctl --address "$(hostname -i):7233" workflow list --namespace ventureos-staging --pagesize 1000 2>/dev/null | wc -l')
  [[ "$workflows_before" == "$workflows_after" ]] || { echo 'Health checks mutated Temporal workflow state' >&2; return 1; }

  CI=true E2E_EXTERNAL_SERVERS=true E2E_BASE_URL=http://localhost:3000 \
    pnpm --filter @ventureos/web run test:e2e

  local users_before users_after
  users_before=$(compose exec -T postgres psql -U "$STAGING_POSTGRES_USER" -d "$STAGING_POSTGRES_DB" -Atc 'select count(*) from users')
  compose restart api worker
  compose up -d --wait api worker web api-ingress web-ingress
  wait_http http://localhost:3001/api/health/ready
  users_after=$(compose exec -T postgres psql -U "$STAGING_POSTGRES_USER" -d "$STAGING_POSTGRES_DB" -Atc 'select count(*) from users')
  [[ "$users_before" == "$users_after" ]] || { echo 'Database persistence check failed after restart' >&2; return 1; }

  CI=true E2E_EXTERNAL_SERVERS=true E2E_BASE_URL=http://localhost:3000 \
    pnpm --filter @ventureos/web run test:e2e

  collect_logs
  if grep -Eiq 'api\.anthropic\.com|api\.etsy\.com|stripe\.com|sendgrid\.com|mailgun\.com' .staging/topology.log; then
    echo 'A forbidden real-provider hostname appeared in runtime logs' >&2
    return 1
  fi
  bash scripts/verify-staging-images.sh "$ENV_FILE"
  echo 'STAGING_SECURITY_GATE_PASS'
}

case "${1:-all}" in
  all) run_gate ;;
  build) build_topology ;;
  up)
    compose up -d --wait postgres temporal minio
    compose run --rm --no-deps temporal-namespace
    compose run --rm --no-deps migrate
    compose run --rm --no-deps seed
    compose up -d --wait api worker web api-ingress web-ingress
    ;;
  logs) compose logs --no-color ;;
  down) collect_logs; cleanup ;;
  *) echo "Usage: $0 {all|build|up|logs|down}" >&2; exit 2 ;;
esac
