import { enforceWorkspaceCapability, prisma } from '@ventureos/database';
import type { Listing, ListingVersion } from '@ventureos/database';

export const MOCK_LISTING_GENERATOR_VERSION = 'mock-listing-generator-v1';

export interface ListingGenerationInput {
  workspaceId: string;
  productId: string;
  productVersionId: string;
  opportunityTitle: string;
  opportunityDescription: string;
  suggestedProductType: string | null;
  estimatedRevenueEur: number | null;
  marketplace?: string;
}

function buildTitle(input: ListingGenerationInput): string {
  const base = `${input.opportunityTitle} — Digital Template Bundle`;
  return base.length > 140 ? `${base.slice(0, 137)}...` : base;
}

function buildDescription(input: ListingGenerationInput): string {
  return `${input.opportunityDescription}\n\nThis is a MOCK draft listing generated by VentureOS Phase 4 (no live marketplace publication has occurred or will occur). Instant digital download.`;
}

function buildTags(input: ListingGenerationInput): string[] {
  const words = input.opportunityTitle
    .toLowerCase()
    .split(/\s+/)
    .filter((w) => w.length > 2)
    .map((w) => w.replace(/[^a-z0-9]/g, ''))
    .filter(Boolean);
  const base = ['digital download', 'template', 'planner', 'printable'];
  return Array.from(new Set([...words, ...base])).slice(0, 13);
}

function buildPrice(input: ListingGenerationInput): number {
  if (input.estimatedRevenueEur && input.estimatedRevenueEur > 0) {
    const heuristic = Math.round((input.estimatedRevenueEur / 10) * 100) / 100;
    return Math.max(0.99, heuristic);
  }
  return 9.99;
}

/**
 * Generates (or regenerates) the mock draft listing for a ProductVersion.
 * Deterministic, no live model calls -- same "mock by default" principle as
 * the Phase 3 board-agent provider. Pulls preview images / files directly
 * from the ProductVersion's current generated assets, so the listing is
 * always consistent with what was actually produced.
 */
export interface GenerateListingResult {
  listing: Listing;
  listingVersion: ListingVersion;
}

export async function generateListing(
  input: ListingGenerationInput,
): Promise<GenerateListingResult> {
  await enforceWorkspaceCapability({
    workspaceId: input.workspaceId,
    capability: 'MARKETPLACE_DRAFT',
    stage: 'DISPATCH',
  });

  await prisma.product.findFirstOrThrow({
    where: {
      id: input.productId,
      workspaceId: input.workspaceId,
      versions: { some: { id: input.productVersionId } },
    },
    select: { id: true },
  });

  const marketplace = input.marketplace ?? 'etsy';

  const listing = await prisma.listing.upsert({
    where: { productId_marketplace: { productId: input.productId, marketplace } },
    update: { productVersionId: input.productVersionId, status: 'DRAFT' },
    create: {
      workspaceId: input.workspaceId,
      productId: input.productId,
      productVersionId: input.productVersionId,
      marketplace,
      status: 'DRAFT',
    },
  });

  const existingVersions = await prisma.listingVersion.count({ where: { listingId: listing.id } });
  const price = buildPrice(input);

  const listingVersion = await prisma.listingVersion.create({
    data: {
      listingId: listing.id,
      versionNumber: existingVersions + 1,
      title: buildTitle(input),
      description: buildDescription(input),
      tags: buildTags(input),
      category: input.suggestedProductType ?? 'Digital Prints & Templates',
      currency: 'EUR',
      priceEur: price,
    },
  });

  await prisma.priceProposal.create({
    data: {
      listingVersionId: listingVersion.id,
      priceEur: price,
      rationale: input.estimatedRevenueEur
        ? `Derived from an estimated revenue of EUR ${input.estimatedRevenueEur} (mock pricing heuristic: revenue / 10).`
        : 'Default mock price -- no estimated revenue was available on the opportunity.',
    },
  });

  const previewAssets = await prisma.productAsset.findMany({
    where: { productVersionId: input.productVersionId, kind: 'PREVIEW_IMAGE' },
    include: { versions: { orderBy: { attempt: 'desc' as const }, take: 1 } },
  });
  let position = 0;
  for (const asset of previewAssets) {
    const latest = asset.versions[0];
    if (!latest) continue;
    await prisma.listingImage.create({
      data: {
        listingVersionId: listingVersion.id,
        productAssetVersionId: latest.id,
        position: position++,
        altText: `${input.opportunityTitle} preview`,
      },
    });
  }

  const fileAssets = await prisma.productAsset.findMany({
    where: {
      productVersionId: input.productVersionId,
      kind: { in: ['PDF_GUIDE', 'SPREADSHEET_TEMPLATE', 'EDITABLE_TEMPLATE'] },
    },
    include: { versions: { orderBy: { attempt: 'desc' as const }, take: 1 } },
  });
  for (const asset of fileAssets) {
    const latest = asset.versions[0];
    if (!latest) continue;
    await prisma.listingFile.create({
      data: {
        listingVersionId: listingVersion.id,
        productAssetVersionId: latest.id,
        displayName: latest.fileName,
      },
    });
  }

  return { listing, listingVersion };
}
